baseURL = "https://anettodev.github.io/"
title = "anetto.dev"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true

paginate = 20
canonifyURLs = true
enableEmoji = true

customSCSS = ["scss/custom.scss"]

[params]
author = "Antonio Netto"
avatarURL = "images/me.jpeg"
images = ["images/an-cover.png"]
description = "ANetto.dev personal website"
keywords = "developer,desenvolvedor,engineer,software,staff,iOS,swift,objective-c,obj-c,c++,C#,python,go,rust"
info = "Sr. Staff Software Engineer"
company = "Inter"
companyURL = "https://inter.co/"

faviconSVG = "/images/favicon.ico"
favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"
touchIcon = "/images/apple-touch-icon.png"

dateFormat = "January 2, 2006"

hideCredits = false
hideCopyright = false

rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false


[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/anettodev/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/anettodev/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/anettodev/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-mastodon fa-2x"
weight = 4
url = "https://me.dm/@anettodev"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@anettodev"

[params.goatCounter]
code = "anettodev"

[params.utterances]
repo = "anettodev/anetto.dev"
issueTerm = "pathname"
theme = "dark"

[markup.highlight]
style = "github-dark"
tabWidth = 4

[module]
[module.hugoVersion]
min = "0.77.0"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
identifier = "fa fa-example-external-site"
weight = 2
url = "https://medium.anetto.dev/"
hrefTargetBlank = true
